version: '3'
services:
  base:
    image: node:lts
    working_dir: /app
    user: node
    volumes:
      - .:/app

  dev:
    extends: 
      service: base
    ports:
      - 3000:3000
      - 24678:24678
    command: npm run dev
